spring.application.name=Staff Management
server.port=8080
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/staff_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# swagger open api
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=admin
spring.security.user.password=admin123
